import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/lib/provider";
import SuspenseLoader from "@/components/suspense-loader";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Suspense } from "react";
import NextTopLoader from "nextjs-toploader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LACON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Suspense fallback={<SuspenseLoader />}>
            <Toaster richColors expand={true} position="top-center" />
            <TooltipProvider>
              {children}
              <NextTopLoader showSpinner={false} color="#6F4E37" />
            </TooltipProvider>
          </Suspense>
        </AppProvider>
      </body>
    </html>
  );
}
